// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice ABI implemented by the Groth16 verifier generated by snarkjs.
interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata proofA,
        uint256[2][2] calldata proofB,
        uint256[2] calldata proofC,
        uint256[9] calldata publicSignals
    ) external view returns (bool);
}
